accelerator: auto
device: auto
cpu_num: 16

image_size: [640, 640]

out_path: runs
exist_ok: True

lucky_number: 10
use_wandb: True
use_tensorboard: False

weight: True # Path to weight or True for auto, False for no pretrained weight
ckpt_path: null # Path to checkpoint file (.ckpt) for resuming training, e.g., "runs/train/v9-dev/checkpoints/last.ckpt"
